# argo-cd-apps/apps/frontend-application.yaml
apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: frontend-test  
  namespace: argocd  
  annotations:  
    argocd.argoproj.io/sync-wave: "1" 
spec:  
  project: devbcn-demo  
  source:  
    repoURL: https://github.com/staslebedenko/application-repo.git  
    targetRevision: HEAD  
    path: infra/frontend/envs/dev  
  destination:  
    server: https://kubernetes.default.svc  
    namespace: devbcn-demo  
  syncPolicy:  
    automated:  
      prune: true  
      selfHeal: true  